### PR TITLE
Update torrc

### PR DESCRIPTION
**Pull request by RobertoVeca**
Otherwise it doesn't work!

### CODE REVIEW

**Comment by ericpaulbishop** [comment]
I see no reason to switch the transparent proxying port. It works just fine for me. Can you justify this somehow, other than "it doesn't work" ?

**Comment by RobertoVeca** [comment]
Hi Erik! sure, I tried to run your script on Kali linux and, without the modify that I propose, the transparent proxy port doesn't open! I should specify it, Sorry! :P

**Comment by ericpaulbishop** [comment]
I have a suspicion that the torrc is just getting installed to the wrong place. There's probably another torrc file that tor is looking at, and then using 9040, the default transparent proxying port.

The problem isn't that the port has to be 9040, it's where the torrc file is going. Look around and see if you can find another torrc file, and then modify that one to 9051, and put the init script back the way it was too. I bet it starts working.

**Comment by ericpaulbishop** [comment]
I am going to close your pull requests for now, but if you can demonstrate that there is a real problem here beyond inaccurate placement of the torrc file, I will re-open.

Alternatively, if you send a patch to fix placement of torrc file on alternate versions of linux such as yours, I would definitely accept that.

**Comment by RobertoVeca** [comment]
Sorry for delay! You were right, I tried to do as you told me, and it worked! Sorry if I wasted your time! :P

**Pull request closed without merging**
